PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE notes(id INTEGER PRIMARY KEY AUTOINCREMENT, tittel TEXT NOT NULL, notat TEXT NOT NULL,tag TEXT NOT NULL,tagid TEXT NOT NULL);
INSERT INTO notes VALUES(0,'hei','heheeh','Low','0');
COMMIT;